### ISSUE TITLE
instalation Issue

### ISSUE THREAD

**Issue by soumboussaha** [sap-labs-france/ev-server#3863]
I keep runing on this Issue when running :

sudo npm install :

"

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/uNetworking/uWebSockets.js.git
npm ERR! 
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-09-19T21_04_07_118Z-debug.log

"

Ubuntu : 20.04 
node js version : v10.19.0

**Comment by soumboussaha** [comment]
This is the logs from :  /root/.npm/_logs/2022-09-19T21_04_07_118Z-debug.log

.
.
.
26643 verbose stack Error: exited with error code: 128
26643 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/pacote/lib/util/finished.js:12:19)
26643 verbose stack     at ChildProcess.emit (events.js:198:13)
26643 verbose stack     at maybeClose (internal/child_process.js:982:16)
26643 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
26644 verbose cwd /home/mobi-taint/ev-server
26645 verbose Linux 5.4.0-125-generic
26646 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
26647 verbose node v10.19.0
26648 verbose npm  v6.14.4
26649 error Error while executing:
### **26649 error /usr/bin/git ls-remote -h -t ssh://git@github.com/uNetworking/uWebSockets.js.git**
26649 error
### **26649 error Host key verification failed.**
26649 error fatal: Could not read from remote repository.
26649 error
26649 error Please make sure you have the correct access rights
26649 error and the repository exists.
26649 error
26649 error exited with error code: 128
26650 verbose exit [ 1, true ]

**Comment by soumboussaha** [comment]
I resolved the problem by updating the nodejs version
