### ISSUE TITLE
Trying to set up local environment for testing

### ISSUE THREAD

**Issue by shooter51** [sap-labs-france/ev-server#3990]
Hello, 

I am trying to set this up local using docker.  I seem to be missing something because I am having issues.  I keep getting this message in the log:

```2022-11-23T01:21:29: PM2 log: App [start:0] starting in -fork mode-
2022-11-22 17:21:29 2022-11-23T01:21:29: PM2 log: App [start:0] online
2022-11-22 17:21:30 AppError: Property '/WSDLEndpoint': must have required property 'baseSecureUrl', Property '/JsonEndpoint': must have required property 'baseSecureUrl'
2022-11-22 17:21:30     at ConfigurationValidatorStorage.validate (/usr/app/dist/webpack:/ev-server/src/validator/SchemaValidator.ts:131:13)
2022-11-22 17:21:30     at ConfigurationValidatorStorage.validateConfigurationSave (/usr/app/dist/webpack:/ev-server/src/storage/validator/ConfigurationValidatorStorage.ts:23:17)
2022-11-22 17:21:30     at Function.getConfig (/usr/app/dist/webpack:/ev-server/src/utils/Configuration.ts:301:74)
2022-11-22 17:21:30     at Function.getNotificationConfig (/usr/app/dist/webpack:/ev-server/src/utils/Configuration.ts:89:40)
2022-11-22 17:21:30     at Object.3305 (/usr/app/dist/webpack:/ev-server/src/notification/NotificationHandler.ts:22:53)
2022-11-22 17:21:30     at __webpack_require__ (/usr/app/dist/webpack:/ev-server/webpack/bootstrap:19:1)
2022-11-22 17:21:30     at Object.516 (/usr/app/dist/webpack:/ev-server/src/integration/billing/BillingIntegration.ts:20:1)
2022-11-22 17:21:30     at __webpack_require__ (/usr/app/dist/webpack:/ev-server/webpack/bootstrap:19:1)
2022-11-22 17:21:30     at Object.8246 (/usr/app/dist/webpack:/ev-server/src/integration/billing/stripe/StripeBillingIntegration.ts:14:1)
2022-11-22 17:21:30     at __webpack_require__ (/usr/app/dist/webpack:/ev-server/webpack/bootstrap:19:1)
2022-11-22 17:21:30     at Object.9341 (/usr/app/dist/webpack:/ev-server/src/integration/billing/BillingFactory.ts:8:1)
2022-11-22 17:21:30     at __webpack_require__ (/usr/app/dist/webpack:/ev-server/webpack/bootstrap:19:1)
2022-11-22 17:21:30     at Object.1395 (/usr/app/dist/webpack:/ev-server/src/async-task/tasks/BillTransactionAsyncTask.ts:4:1)
2022-11-22 17:21:30     at __webpack_require__ (/usr/app/dist/webpack:/ev-server/webpack/bootstrap:19:1)
2022-11-22 17:21:30     at Object.7654 (/usr/app/dist/webpack:/ev-server/src/async-task/AsyncTaskManager.ts:7:1)
2022-11-22 17:21:30     at __webpack_require__ (/usr/app/dist/webpack:/ev-server/webpack/bootstrap:19:1) {
2022-11-22 17:21:30   params: {
2022-11-22 17:21:30     errorCode: 400,
2022-11-22 17:21:30     message: "Property '/WSDLEndpoint': must have required property 'baseSecureUrl', Property '/JsonEndpoint': must have required property 'baseSecureUrl'",
2022-11-22 17:21:30     module: 'ConfigurationValidatorStorage',
2022-11-22 17:21:30     method: 'validate',
2022-11-22 17:21:30     detailedMessages: { errors: [Array], data: [Object], schema: [Object] }
2022-11-22 17:21:30   }
2022-11-22 17:21:30 }
2022-11-22 17:21:30 2022-11-23T01:21:30: PM2 log: App [start:0] exited with code [1] via signal [SIGINT]``

**Comment by Anmirazik** [comment]
you must copy the contents of your config.json file in assets into the config.json files in docker folder , the current config.json file schema inside the docker file cannot be use
